export const INITIAL_EMPLOYERS = [
  { name: "SPIN", category: "Education & Educational Partners", website: "https://spininc.org/careers/" },
  { name: "Children’s Village", category: "Education & Educational Partners", website: "https://childrensvillagephila.org/careers/" },
  { name: "Acelero", category: "Education & Educational Partners", website: "https://www.acelero.net/careers/" },
  { name: "School District of Philadelphia", category: "Education & Educational Partners", website: "https://jobs.philasd.org/" },
  { name: "Temple University", category: "Education & Educational Partners", website: "https://careers.temple.edu/" },
  { name: "University of Pennsylvania (UPenn)", category: "Education & Educational Partners", website: "https://www.hr.upenn.edu/PennHR/careers-at-penn" },
  { name: "Devereux", category: "Education & Educational Partners", website: "http://www.cccareers.net/Applicants/Apply.aspx?Div=CCC&RecrID=305" },
  { name: "Bank of America", category: "Financial & Banking Partners", website: "https://careers.bankofamerica.com/" },
  { name: "Santander", category: "Financial & Banking Partners", website: "https://jobs.santanderbank.com/" },
  { name: "M&T Bank", category: "Financial & Banking Partners", website: "https://www.mtb.com/careers" },
  { name: "Asian Bank", category: "Financial & Banking Partners", website: "https://www.asianbank.com/careers" },
  { name: "Lincoln Financial", category: "Financial & Banking Partners", website: "https://jobs.lincolnfinancial.com/" },
  { name: "Vanguard", category: "Financial & Banking Partners", website: "https://www.vanguardjobs.com/" },
  { name: "TD Bank", category: "Financial & Banking Partners", website: "https://jobs.td.com/en-US/" },
  { name: "PNC", category: "Financial & Banking Partners", website: "https://careers.pnc.com/" },
  { name: "Bala Engineers", category: "Engineering & Industry Partners", website: "https://www.bala.com/careers" },
  { name: "Urban Engineers", category: "Engineering & Industry Partners", website: "https://urbanengineers.com/careers" },
  { name: "DVM Power", category: "Engineering & Industry Partners", website: "https://dvmpower.com/careers" },
  { name: "Trane Technologies", category: "Engineering & Industry Partners", website: "https://careers.tranetechnologies.com/" },
  { name: "KAKS & Company", category: "Engineering & Industry Partners", website: "https://kakscompany.com/careers" },
  { name: "IFM", category: "Engineering & Industry Partners", website: "https://www.ifm.com/us/en/shared/careers" },
  { name: "Johnson & Johnson", category: "Engineering & Industry Partners", website: "https://jobs.jnj.com/" },
  { name: "City of Philadelphia", category: "Governmental Partners", website: "https://www.phila.gov/jobs/" },
  { name: "Montgomery County", category: "Governmental Partners", website: "https://www.montcopa.org/jobs" },
  { name: "Center City District", category: "Governmental Partners", website: "https://www.centercityphila.org/about/jobs" },
  { name: "SEPTA", category: "Governmental Partners", website: "https://jobs.septa.org/" },
  { name: "PHMC", category: "Nonprofit & Community Organizations", website: "https://www.phmc.org/site/careers" },
  { name: "JEVS", category: "Nonprofit & Community Organizations", website: "https://www.jevshumanservices.org/careers/" },
  { name: "World Affairs Council", category: "Nonprofit & Community Organizations", website: "https://wacphila.org/join-our-team/" },
  { name: "Connect the Dots", category: "Nonprofit & Community Organizations", website: "https://www.connectthedots.org/careers" },
  { name: "Ronald McDonald House", category: "Nonprofit & Community Organizations", website: "https://www.philarmh.org/careers/" },
  { name: "Rivers Casino", category: "Hospitality / Food & Beverage Partners", website: "https://www.riverscasino.com/philadelphia/careers" },
  { name: "Panda Express", category: "Hospitality / Food & Beverage Partners", website: "https://www.pandacareers.com/" },
  { name: "Marriott Old City", category: "Hospitality / Food & Beverage Partners", website: "https://jobs.marriott.com/" },
  { name: "Cook N Solo", category: "Hospitality / Food & Beverage Partners", website: "https://www.cooknsolo.com/careers" },
  { name: "Loews Hotel", category: "Hospitality / Food & Beverage Partners", website: "https://www.loewshotels.com/careers" },
  { name: "Marshall's Distribution Center", category: "Manufacturing Partners", website: "https://jobs.tjx.com/" },
  { name: "La Colombe / Chobani", category: "Manufacturing Partners", website: "https://www.lacolombe.com/pages/careers" },
  { name: "Deval LifeCycle", category: "Manufacturing Partners", website: "https://devallifecycle.com/careers" },
  { name: "Newman Paperboard", category: "Manufacturing Partners", website: "https://newmanpaperboard.com/careers" },
  { name: "Just Born", category: "Manufacturing Partners", website: "https://www.justborn.com/careers" },
  { name: "ACCU Staffing", category: "Staffing & Temp Agency Partners", website: "https://www.accustaffing.com/" },
  { name: "Express Employment Professionals", category: "Staffing & Temp Agency Partners", website: "https://www.expresspros.com/philadelphiapa/" }
];
